### ISSUE TITLE
Unable to install python-sat due to pypblib

### ISSUE THREAD

**Issue by shivamjgandhi** [andertavares/mlbf#6]
Hello,
I get the following error when I try to run the command `pip install python-sat[pblib,aiger]`:

```
ERROR: Failed building wheel for pypblib
  Running setup.py clean for pypblib
Failed to build pypblib
Installing collected packages: pypblib, py-aiger-cnf
    Running setup.py install for pypblib ... error
    ERROR: Command errored out with exit status 1:

```
Any idea on how I can fix this? Thanks!

**Comment by andertavares** [comment]
Hi! Thanks for your interest in this project!

The error is related to the installation of python-sat. They (https://pysathq.github.io/installation.html) suggest installing without pblib and aiger when the default installation fails. Please try:
`pip install python-sat`
And let me know if it works.

**Comment by shivamjgandhi** [comment]
Looks like this works. Thank you!

**Comment by Aymenbel** [comment]
same error, how can i fix it ?
